// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU8zQNE6sKpagVz8WqnegnbXel15etwpI',
    appId: '1:216809890780:web:a800733fc4bc4df2026519',
    messagingSenderId: '216809890780',
    projectId: 'compsmart-f2df0',
    authDomain: 'compsmart-f2df0.firebaseapp.com',
    storageBucket: 'compsmart-f2df0.appspot.com',
    measurementId: 'G-C6990BHPEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkVaQ8yE1lHcQ31mB28Oy882XEMTB4_l0',
    appId: '1:216809890780:android:414126e4c66caa20026519',
    messagingSenderId: '216809890780',
    projectId: 'compsmart-f2df0',
    storageBucket: 'compsmart-f2df0.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiIAe6s6u6Rn9ZnBrNxx0pOY954pCQ93E',
    appId: '1:216809890780:ios:d86eff5160074d88026519',
    messagingSenderId: '216809890780',
    projectId: 'compsmart-f2df0',
    storageBucket: 'compsmart-f2df0.appspot.com',
    iosBundleId: 'com.example.musicproject.RunnerTests',
  );
}
